version: '3.8'
services:
  db:
    image: postgres:15
    container_name: Telegram-Bot-For-Labs
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
